# Assignmnet 6 

# Text Summarisation for different languages

## Japanese Language

## Import needed modules

In [1]:
# Importing the stopwords corpus from NLTK
from nltk.corpus import stopwords

# Importing the cosine_distance function from NLTK cluster utility
from nltk.cluster.util import cosine_distance

# Importing numpy library and aliasing it as 'np'
import numpy as np

# Importing the networkx library and aliasing it as 'nx'
import networkx as nx

## Open file and split into sentences

In [2]:
# Opening the text file in read mode
file = open("C:\\Users\\himav\\Downloads\\Japanese.txt", encoding="utf-8")

#This file contains one paragraph of multiple sentences
filedata = file.readlines()

# Extracting the first paragraph from the file data and splitting it into sentences
article = filedata[0].split(" ")

# Initializing an empty list to store the tokenized sentences
sentences = []

# Looping through each sentence in the article
for sentence in article:
    # Printing the sentence
    print(sentence)
    # Tokenizing the sentence by replacing non-alphabetic characters with spaces and then splitting on spaces
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

この言語の先史や、いつ日本に初めて登場したかについてはほとんど知られていません。西暦
3
世紀の中国の文書にはいくつかの日本語の単語が記録されていましたが、実質的な古日本語の文書は
8
世紀まで出現しませんでした。平安時代
(794
～
1185
年)
から、中国と日本の語彙が大量に流入し、中期初期日本語の音韻論に影響を与えました。中期後期日本語
(1185
～
1600
年)
では、文法が大幅に変更され、ヨーロッパからの外来語が初めて登場しました。標準語の基礎は近世日本の時代（17世紀前半～19世紀半ば）に関西地方から江戸地方（現在の東京）に移りました。
1853
年に日本の自主的鎖国が終了した後、ヨーロッパ言語からの外来語の流れが大幅に増加し、英語のルーツに由来する単語が急増しました。



## Our data: a list of sentences

In [3]:
# Printing the list of tokenized sentences
print("Sentences are ", sentences)

Sentences are  [['\ufeffこの言語の先史や、いつ日本に初めて登場したかについてはほとんど知られていません。西暦'], ['3'], ['世紀の中国の文書にはいくつかの日本語の単語が記録されていましたが、実質的な古日本語の文書は'], ['8'], ['世紀まで出現しませんでした。平安時代'], ['(794'], ['～'], ['1185'], ['年)'], ['から、中国と日本の語彙が大量に流入し、中期初期日本語の音韻論に影響を与えました。中期後期日本語'], ['(1185'], ['～'], ['1600'], ['年)'], ['では、文法が大幅に変更され、ヨーロッパからの外来語が初めて登場しました。標準語の基礎は近世日本の時代（17世紀前半～19世紀半ば）に関西地方から江戸地方（現在の東京）に移りました。'], ['1853'], ['年に日本の自主的鎖国が終了した後、ヨーロッパ言語からの外来語の流れが大幅に増加し、英語のルーツに由来する単語が急増しました。\n']]


## Function to calculate similarity

In [4]:
def sentence_similarity(sent1, sent2 ):
    # Convert both sentences to lowercase
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    
    # Combine both sentences to create a list of all unique words
    all_words = list(set(sent1 + sent2))
    
    # Initialize vectors to represent word frequency in each sentence
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
    
    # build the vector for the first sentence
    for w in sent1:
        vector1[all_words.index(w)] += 1
    
    # build the vector for the second sentence
    for w in sent2:
        vector2[all_words.index(w)] += 1
        
    # Calculate cosine similarity between the two vectors
    return 1 - cosine_distance(vector1, vector2)

## Create the similarity matrix

In [5]:
# Initialize a square matrix to store similarity scores between sentences
similarity_matrix = np.zeros((len(sentences), len(sentences)))

# Loop through each pair of sentences
for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2: #ignore if both are same sentences
            continue
        # Calculate the similarity score between the current pair of sentences
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

# Print the similarity matrix
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Get the pagerank scores

In [6]:
# Step 3 - Rank sentences in similarity martix

# Convert the similarity matrix to a graph
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)

# Calculate the PageRank scores for each node (sentence) in the graph
scores = nx.pagerank(sentence_similarity_graph)

# Print the PageRank scores for each sentence
print("scores", scores)

scores {0: 0.0252111715444404, 1: 0.0252111715444404, 2: 0.0252111715444404, 3: 0.0252111715444404, 4: 0.0252111715444404, 5: 0.0252111715444404, 6: 0.16806369248056863, 7: 0.0252111715444404, 8: 0.16806369248056863, 9: 0.0252111715444404, 10: 0.0252111715444404, 11: 0.16806369248056863, 12: 0.0252111715444404, 13: 0.16806369248056863, 14: 0.0252111715444404, 15: 0.0252111715444404, 16: 0.0252111715444404}


## Sort sentences by pagerank

In [7]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in
enumerate(sentences)), reverse=True)

# Print the indexes and sentences of the top-ranked sentences in order
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.16806369248056863, ['～']), (0.16806369248056863, ['～']), (0.16806369248056863, ['年)']), (0.16806369248056863, ['年)']), (0.0252111715444404, ['\ufeffこの言語の先史や、いつ日本に初めて登場したかについてはほとんど知られていません。西暦']), (0.0252111715444404, ['年に日本の自主的鎖国が終了した後、ヨーロッパ言語からの外来語の流れが大幅に増加し、英語のルーツに由来する単語が急増しました。\n']), (0.0252111715444404, ['世紀まで出現しませんでした。平安時代']), (0.0252111715444404, ['世紀の中国の文書にはいくつかの日本語の単語が記録されていましたが、実質的な古日本語の文書は']), (0.0252111715444404, ['では、文法が大幅に変更され、ヨーロッパからの外来語が初めて登場しました。標準語の基礎は近世日本の時代（17世紀前半～19世紀半ば）に関西地方から江戸地方（現在の東京）に移りました。']), (0.0252111715444404, ['から、中国と日本の語彙が大量に流入し、中期初期日本語の音韻論に影響を与えました。中期後期日本語']), (0.0252111715444404, ['8']), (0.0252111715444404, ['3']), (0.0252111715444404, ['1853']), (0.0252111715444404, ['1600']), (0.0252111715444404, ['1185']), (0.0252111715444404, ['(794']), (0.0252111715444404, ['(1185'])]


## Pick the top "n" sentences

In [9]:
#Step 5 - How many sentences to pick

# Prompt the user to input the number of sentences they want in the summary
n = int(input("How many sentences do you want in the summary? ")) # n=4

# Initialize an empty list to store the summarized sentences
summarize_text = []

# Iterate over the top n ranked sentences
for i in range(n):
    
    # Append the sentence to the summarized text list, joining the words into a single string
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 4


## Finish off by printing summary

In [10]:
# Step 6 - # Output the summarized text by joining the sentences into a single string with a period and space between each sentence
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 ～. ～. 年). 年)


## Korean Language

## Import needed modules

In [11]:
# Importing the stopwords corpus from NLTK
from nltk.corpus import stopwords

# Importing the cosine_distance function from NLTK cluster utility
from nltk.cluster.util import cosine_distance

# Importing numpy library and aliasing it as 'np'
import numpy as np

# Importing the networkx library and aliasing it as 'nx'
import networkx as nx

## Open file and split into sentences

In [12]:
# Opening the text file in read mode
file = open("C:\\Users\\himav\\Downloads\\Japanese.txt", encoding="utf-8")

#This file contains one paragraph of multiple sentences
filedata = file.readlines()

# Extracting the first paragraph from the file data and splitting it into sentences
article = filedata[0].split(". ")

# Initializing an empty list to store the tokenized sentences
sentences = []

# Looping through each sentence in the article
for sentence in article:
    # Printing the sentence
    print(sentence)
    # Tokenizing the sentence by replacing non-alphabetic characters with spaces and then splitting on spaces
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

この言語の先史や、いつ日本に初めて登場したかについてはほとんど知られていません。西暦 3 世紀の中国の文書にはいくつかの日本語の単語が記録されていましたが、実質的な古日本語の文書は 8 世紀まで出現しませんでした。平安時代 (794 ～ 1185 年) から、中国と日本の語彙が大量に流入し、中期初期日本語の音韻論に影響を与えました。中期後期日本語 (1185 ～ 1600 年) では、文法が大幅に変更され、ヨーロッパからの外来語が初めて登場しました。標準語の基礎は近世日本の時代（17世紀前半～19世紀半ば）に関西地方から江戸地方（現在の東京）に移りました。 1853 年に日本の自主的鎖国が終了した後、ヨーロッパ言語からの外来語の流れが大幅に増加し、英語のルーツに由来する単語が急増しました。



## Our data: a list of sentences

In [13]:
# Printing the list of tokenized sentences
print("Sentences are ", sentences)

Sentences are  [['\ufeffこの言語の先史や、いつ日本に初めて登場したかについてはほとんど知られていません。西暦', '3', '世紀の中国の文書にはいくつかの日本語の単語が記録されていましたが、実質的な古日本語の文書は', '8', '世紀まで出現しませんでした。平安時代', '(794', '～', '1185', '年)', 'から、中国と日本の語彙が大量に流入し、中期初期日本語の音韻論に影響を与えました。中期後期日本語', '(1185', '～', '1600', '年)', 'では、文法が大幅に変更され、ヨーロッパからの外来語が初めて登場しました。標準語の基礎は近世日本の時代（17世紀前半～19世紀半ば）に関西地方から江戸地方（現在の東京）に移りました。', '1853', '年に日本の自主的鎖国が終了した後、ヨーロッパ言語からの外来語の流れが大幅に増加し、英語のルーツに由来する単語が急増しました。\n']]


## Function to calculate similarity

In [14]:
def sentence_similarity(sent1, sent2 ):
    # Convert both sentences to lowercase
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    
    # Combine both sentences to create a list of all unique words
    all_words = list(set(sent1 + sent2))
    
    # Initialize vectors to represent word frequency in each sentence
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
    
    # build the vector for the first sentence
    for w in sent1:
        vector1[all_words.index(w)] += 1
    
    # build the vector for the second sentence
    for w in sent2:
        vector2[all_words.index(w)] += 1
        
    # Calculate cosine similarity between the two vectors
    return 1 - cosine_distance(vector1, vector2)

## Create the similarity matrix

In [15]:
# Initialize a square matrix to store similarity scores between sentences
similarity_matrix = np.zeros((len(sentences), len(sentences)))

# Loop through each pair of sentences
for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2: #ignore if both are same sentences
            continue
        # Calculate the similarity score between the current pair of sentences
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

# Print the similarity matrix
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.]]


## Get the pagerank scores

In [16]:
# Step 3 - Rank sentences in similarity martix

# Convert the similarity matrix to a graph
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)

# Calculate the PageRank scores for each node (sentence) in the graph
scores = nx.pagerank(sentence_similarity_graph)

# Print the PageRank scores for each sentence
print("scores", scores)

scores {0: 1.0}


## Sort sentences by pagerank

In [17]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in
enumerate(sentences)), reverse=True)

# Print the indexes and sentences of the top-ranked sentences in order
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(1.0, ['\ufeffこの言語の先史や、いつ日本に初めて登場したかについてはほとんど知られていません。西暦', '3', '世紀の中国の文書にはいくつかの日本語の単語が記録されていましたが、実質的な古日本語の文書は', '8', '世紀まで出現しませんでした。平安時代', '(794', '～', '1185', '年)', 'から、中国と日本の語彙が大量に流入し、中期初期日本語の音韻論に影響を与えました。中期後期日本語', '(1185', '～', '1600', '年)', 'では、文法が大幅に変更され、ヨーロッパからの外来語が初めて登場しました。標準語の基礎は近世日本の時代（17世紀前半～19世紀半ば）に関西地方から江戸地方（現在の東京）に移りました。', '1853', '年に日本の自主的鎖国が終了した後、ヨーロッパ言語からの外来語の流れが大幅に増加し、英語のルーツに由来する単語が急増しました。\n'])]


## Pick the top "n" sentences

In [18]:
#Step 5 - How many sentences to pick

# Prompt the user to input the number of sentences they want in the summary
n = int(input("How many sentences do you want in the summary? ")) # n=1

# Initialize an empty list to store the summarized sentences
summarize_text = []

# Iterate over the top n ranked sentences
for i in range(n):
    
    # Append the sentence to the summarized text list, joining the words into a single string
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 1


## Finish off by printing summary

In [19]:
# Step 6 - # Output the summarized text by joining the sentences into a single string with a period and space between each sentence
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 この言語の先史や、いつ日本に初めて登場したかについてはほとんど知られていません。西暦 3 世紀の中国の文書にはいくつかの日本語の単語が記録されていましたが、実質的な古日本語の文書は 8 世紀まで出現しませんでした。平安時代 (794 ～ 1185 年) から、中国と日本の語彙が大量に流入し、中期初期日本語の音韻論に影響を与えました。中期後期日本語 (1185 ～ 1600 年) では、文法が大幅に変更され、ヨーロッパからの外来語が初めて登場しました。標準語の基礎は近世日本の時代（17世紀前半～19世紀半ば）に関西地方から江戸地方（現在の東京）に移りました。 1853 年に日本の自主的鎖国が終了した後、ヨーロッパ言語からの外来語の流れが大幅に増加し、英語のルーツに由来する単語が急増しました。



## Chinese Language

## Import needed modules

In [20]:
# Importing the stopwords corpus from NLTK
from nltk.corpus import stopwords

# Importing the cosine_distance function from NLTK cluster utility
from nltk.cluster.util import cosine_distance

# Importing numpy library and aliasing it as 'np'
import numpy as np

# Importing the networkx library and aliasing it as 'nx'
import networkx as nx

## Open file and split into sentences

In [21]:
# Opening the text file in read mode
file = open("C:\\Users\\himav\\Downloads\\Chinese.txt", encoding="utf-8")

#This file contains one paragraph of multiple sentences
filedata = file.readlines()

# Extracting the first paragraph from the file data and splitting it into sentences
article = filedata[0].split(". ")

# Initializing an empty list to store the tokenized sentences
sentences = []

# Looping through each sentence in the article
for sentence in article:
    # Printing the sentence
    print(sentence)
    # Tokenizing the sentence by replacing non-alphabetic characters with spaces and then splitting on spaces
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

漢語是世界上最古老的文字，至少有六千年的歷史。在龜殼中發現的漢字銘文可以追溯到商代1（公元前 1766-1123 年），證明書面語言已經存在了 3000 多年。中文書面語言使用單一獨特的符號或字元來表示詞彙中的每個單字。絕大多數字符都是有意義的口頭聲音的書面版本。一本大字典通常包含 40,000 個字元。儘管隨著時間的推移，由於革命和政治變化，書面系統發生了變化，但語言的原理以及符號和字符基本上保持不變。



## Our data: a list of sentences

In [22]:
# Printing the list of tokenized sentences
print("Sentences are ", sentences)

Sentences are  [['\ufeff漢語是世界上最古老的文字，至少有六千年的歷史。在龜殼中發現的漢字銘文可以追溯到商代1（公元前', '1766-1123', '年），證明書面語言已經存在了', '3000', '多年。中文書面語言使用單一獨特的符號或字元來表示詞彙中的每個單字。絕大多數字符都是有意義的口頭聲音的書面版本。一本大字典通常包含', '40,000', '個字元。儘管隨著時間的推移，由於革命和政治變化，書面系統發生了變化，但語言的原理以及符號和字符基本上保持不變。\n']]


## Function to calculate similarity

In [23]:
def sentence_similarity(sent1, sent2 ):
    # Convert both sentences to lowercase
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    
    # Combine both sentences to create a list of all unique words
    all_words = list(set(sent1 + sent2))
    
    # Initialize vectors to represent word frequency in each sentence
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
    
    # build the vector for the first sentence
    for w in sent1:
        vector1[all_words.index(w)] += 1
    
    # build the vector for the second sentence
    for w in sent2:
        vector2[all_words.index(w)] += 1
        
    # Calculate cosine similarity between the two vectors
    return 1 - cosine_distance(vector1, vector2)

## Create the similarity matrix

In [24]:
# Initialize a square matrix to store similarity scores between sentences
similarity_matrix = np.zeros((len(sentences), len(sentences)))

# Loop through each pair of sentences
for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2: #ignore if both are same sentences
            continue
        # Calculate the similarity score between the current pair of sentences
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

# Print the similarity matrix
print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.]]


## Get the pagerank scores

In [25]:
# Step 3 - Rank sentences in similarity martix

# Convert the similarity matrix to a graph
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)

# Calculate the PageRank scores for each node (sentence) in the graph
scores = nx.pagerank(sentence_similarity_graph)

# Print the PageRank scores for each sentence
print("scores", scores)

scores {0: 1.0}


## Sort sentences by pagerank

In [26]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in
enumerate(sentences)), reverse=True)

# Print the indexes and sentences of the top-ranked sentences in order
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(1.0, ['\ufeff漢語是世界上最古老的文字，至少有六千年的歷史。在龜殼中發現的漢字銘文可以追溯到商代1（公元前', '1766-1123', '年），證明書面語言已經存在了', '3000', '多年。中文書面語言使用單一獨特的符號或字元來表示詞彙中的每個單字。絕大多數字符都是有意義的口頭聲音的書面版本。一本大字典通常包含', '40,000', '個字元。儘管隨著時間的推移，由於革命和政治變化，書面系統發生了變化，但語言的原理以及符號和字符基本上保持不變。\n'])]


## Pick the top "n" sentences

In [27]:
#Step 5 - How many sentences to pick

# Prompt the user to input the number of sentences they want in the summary
n = int(input("How many sentences do you want in the summary? ")) # n=1

# Initialize an empty list to store the summarized sentences
summarize_text = []

# Iterate over the top n ranked sentences
for i in range(n):
    
    # Append the sentence to the summarized text list, joining the words into a single string
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary? 1


## Finish off by printing summary

In [28]:
# Step 6 - Output the summarized text by joining the sentences into a single string with a period and space between each sentence
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 漢語是世界上最古老的文字，至少有六千年的歷史。在龜殼中發現的漢字銘文可以追溯到商代1（公元前 1766-1123 年），證明書面語言已經存在了 3000 多年。中文書面語言使用單一獨特的符號或字元來表示詞彙中的每個單字。絕大多數字符都是有意義的口頭聲音的書面版本。一本大字典通常包含 40,000 個字元。儘管隨著時間的推移，由於革命和政治變化，書面系統發生了變化，但語言的原理以及符號和字符基本上保持不變。

